# Generated by Django 6.0.3 on 2026-03-20 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_legacy_password_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSnapshot',
            fields=[
                ('snapshot_key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('saved_at_utc', models.CharField(max_length=32)),
                ('scope', models.CharField(blank=True, max_length=32, null=True)),
                ('coverage_filter', models.CharField(blank=True, max_length=32, null=True)),
                ('source_mode', models.CharField(blank=True, max_length=64, null=True)),
                ('payload_json', models.TextField()),
                ('alerts_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'AlertSnapshots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('disaster_id', models.AutoField(db_column='Disaster_id', primary_key=True, serialize=False)),
                ('verify_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('media', models.BinaryField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image')], max_length=10, null=True)),
                ('disaster_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('address_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Disasters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('DISASTER', 'Disaster Report'), ('SOS', 'SOS Request'), ('UPDATE', 'Status Update'), ('WARNING', 'System Warning'), ('INFO', 'Information')], max_length=20)),
                ('content', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_alert_user_id_d35048_idx'), models.Index(fields=['alert_type', '-created_at'], name='core_alert_alert_t_aa335f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ALERT', 'Alert Notification'), ('MESSAGE', 'Direct Message'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebSocketSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('connection_type', models.CharField(choices=[('realtime', 'Real-time'), ('notifications', 'Notifications')], max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websocket_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_websoc_user_id_a5c4fe_idx'), models.Index(fields=['connection_type', 'is_active'], name='core_websoc_connect_df3038_idx')],
            },
        ),
    ]
