# Generated by Django 4.2.13 on 2026-03-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alertsnapshot_disaster_alert_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsnapshot',
            options={'managed': True},
        ),
    ]
