from django.urls import path, re_path
from django.views.generic.base import RedirectView

from core import views

urlpatterns = [
    path("health/db", views.db_health, name="db_health"),
    path("api/internal/health", views.api_internal_health, name="api_internal_health"),
    path("api/internal/alerts", views.api_internal_alerts, name="api_internal_alerts"),
    path("api/internal/alerts/", views.api_internal_alerts),
    path("api/internal/sources/status", views.api_internal_sources_status, name="api_internal_sources_status"),
    path("api/internal/sources/status/", views.api_internal_sources_status),
    path("api/internal/sync", views.api_internal_sync, name="api_internal_sync"),
    path("api/internal/sync/", views.api_internal_sync),
    path("assets/<path:asset_path>", views.spa_asset, name="spa_asset"),
    path(
        "model_1_only/<path:asset_path>",
        views.spa_public_scoped_asset,
        {"scope": "model_1_only"},
        name="spa_model_1_asset",
    ),
    path(
        "model_2_only/<path:asset_path>",
        views.spa_public_scoped_asset,
        {"scope": "model_2_only"},
        name="spa_model_2_asset",
    ),
    path(
        "model_3_only/<path:asset_path>",
        views.spa_public_scoped_asset,
        {"scope": "model_3_only"},
        name="spa_model_3_asset",
    ),
    path("", views.spa_index, name="index"),
    path("login", views.spa_index, name="login"),
    path("login/", views.spa_index),
    path("signup", views.spa_index, name="signup"),
    path("signup/", views.spa_index),
    path("change-password", views.spa_index, name="change_password"),
    path("change-password/", views.spa_index),
    path("auth/callback", views.authorize, name="authorize"),
    path("oauth2/callback", views.authorize, name="authorize_alt"),
    path("oauth2callback", views.authorize, name="authorize_legacy"),
    path("login/google", views.login_google, name="login_google"),
    path("home", views.spa_index, name="home"),
    path(
        "admin",
        RedirectView.as_view(url="/django-admin/", permanent=False),
        name="admin_panel",
    ),
    path("admin/", RedirectView.as_view(url="/django-admin/", permanent=False)),
    path(
        "admin/user-view",
        RedirectView.as_view(url="/django-admin/auth/user/", permanent=False),
        name="admin_user_view",
    ),
    path("admin/user-view/", RedirectView.as_view(url="/django-admin/auth/user/", permanent=False)),
    path("alerts", views.spa_index, name="spa_alerts"),
    path("report", views.spa_index, name="spa_report"),
    path("sos", views.spa_index, name="spa_sos"),
    path("analysis", views.spa_index, name="spa_analysis"),
    path("ngos", views.spa_index, name="spa_ngos"),
    path("weather", views.spa_index, name="spa_weather"),
    path("settings", views.spa_index, name="spa_settings"),
    path("profile", views.spa_index, name="spa_profile"),
    path("profile/", views.spa_index),
    path("hill90", views.spa_index, name="spa_hill90"),
    path("hill90/", views.spa_index),
    path("mobile", views.spa_index, name="mobile_landing"),
    path("mobile/home", views.spa_index, name="mobile_home"),
    path("mobile/profile/update", views.spa_index, name="mobile_profile_update"),
    path("mobile/details", views.spa_index, name="mobile_details"),
    path("mobile/alerts", views.spa_index, name="mobile_alerts"),
    path("mobile/sos", views.spa_index, name="mobile_sos"),
    path("mobile/sos-basic", views.spa_index, name="mobile_sos_basic"),
    path("mobile/sos-app", views.spa_index, name="mobile_sos_app_download_page"),
    path("mobile/sos-app/download", views.mobile_sos_app_download_apk, name="mobile_sos_app_download_apk"),
    path(
        "mobile/sos-app/download/history/<path:apk_filename>",
        views.mobile_sos_app_download_version,
        name="mobile_sos_app_download_version",
    ),
    path("mobile-sos-sw.js", views.mobile_sos_service_worker, name="mobile_sos_service_worker"),
    path("mobile/manifest.json", views.mobile_sos_manifest, name="mobile_sos_manifest"),
    path("api/mobile/sos/payload", views.mobile_sos_payload, name="mobile_sos_payload"),
    path(
        "api/mobile/analysis/module-one",
        views.mobile_analysis_module_one_assets,
        name="mobile_analysis_module_one_assets",
    ),
    path(
        "mobile/analysis/asset/<path:asset_id>",
        views.mobile_analysis_asset,
        name="mobile_analysis_asset",
    ),
    path("mobile/analysis", views.spa_index, name="mobile_analysis"),
    path("mobile/organization", views.spa_index, name="mobile_organization"),
    path("mobile/satellite", views.spa_index, name="mobile_satellite"),
    path("mobile/admin", views.spa_index, name="mobile_admin_panel"),
    path("mobile/hill90", views.spa_index, name="mobile_live_alerts_check"),
    path(
        "mobile/live-alerts-check",
        views.spa_index,
        name="mobile_live_alerts_check_legacy",
    ),
    path(
        "api/mobile/hill90/diagnostics",
        views.mobile_hill90_diagnostics,
        name="mobile_hill90_diagnostics",
    ),
    path(
        "api/mobile/hill90/force-sync",
        views.mobile_hill90_force_sync,
        name="mobile_hill90_force_sync",
    ),
    path("api/mobile/live-alerts", views.mobile_live_alerts, name="mobile_live_alerts"),
    path("api/mobile/translate-alert", views.api_mobile_translate_alert, name="api_mobile_translate_alert"),
    path("api/auth/session", views.api_auth_session, name="api_auth_session"),
    path("api/auth/session/", views.api_auth_session),
    path("api/auth/profile", views.api_auth_profile, name="api_auth_profile"),
    path("api/auth/profile/", views.api_auth_profile),
    path("api/auth/csrf", views.api_auth_csrf, name="api_auth_csrf"),
    path("api/auth/csrf/", views.api_auth_csrf),
    path("api/auth/login", views.api_auth_login, name="api_auth_login"),
    path("api/auth/login/", views.api_auth_login),
    path("api/auth/signup", views.api_auth_signup, name="api_auth_signup"),
    path("api/auth/signup/", views.api_auth_signup),
    path("api/auth/change-password", views.api_auth_change_password, name="api_auth_change_password"),
    path("api/auth/change-password/", views.api_auth_change_password),
    path("api/auth/logout", views.api_auth_logout, name="api_auth_logout"),
    path("api/auth/logout/", views.api_auth_logout),
    path("api/ws-token", views.api_ws_token, name="api_ws_token"),
    path("api/weather-grid", views.api_weather_grid, name="api_weather_grid"),
    path("api/report-disaster", views.api_report_disaster, name="api_report_disaster"),
    path("logout", views.logout, name="logout"),
    path("weather-grid", views.spa_index, name="get_weather_grid"),
    path("api/get-ngos", views.get_nearby_ngos, name="get_nearby_ngos"),
    path("api/live-ngos", views.live_ngos, name="live_ngos"),
    path("api/contact-request", views.contact_request, name="contact_request"),
    path("get-all-users", views.get_all_users, name="get_all_users"),
    path(
        "admin/reset-user-password",
        views.admin_reset_user_password,
        name="admin_reset_user_password",
    ),
    path("block-user", views.block_user, name="block_user"),
    path("get-all-incidents", views.get_all_incidents, name="get_all_incidents"),
    path("verify-incident", views.verify_incident, name="verify_incident"),
    path("delete-incident", views.delete_incident, name="delete_incident"),
    path("report-disaster", views.spa_index, name="report_disaster"),
    re_path(r"^(?P<asset_path>[^/]+\.[^/]+)$", views.spa_public_asset, name="spa_public_asset"),
]
